### ISSUE TITLE
Not implement "FormTypeInterface"

### ISSUE THREAD

**Issue by Quovandius** [artgris/MediaBundle#10]
Hi,

I have just discover your bundle, and try it.

I have an error when i display the form with MediaType like this : 
HTTP 500 Internal Server Error
Could not load type "Artgris\Bundle\MediaBundle\Type\MediaType": class does not implement "Symfony\Component\Form\FormTypeInterface".

I have add this use : use Artgris\Bundle\MediaBundle\Type\MediaType;

How can i fix this ?

**Comment by Arkounay** [comment]
Hi,

You should import this for forms: `use Artgris\Bundle\MediaBundle\Form\Type\MediaType;`

**Comment by Quovandius** [comment]
Hi,

thx for this fast reply =)
Yes its works
