### ISSUE TITLE
Can't add/remove from media_collection when editing entity

### ISSUE THREAD

**Issue by mitjana** [artgris/MediaBundle#15]
Hello,
This bundle is very useful but I can't add or remove media from my entity.
When I create the entity medias are added but when I try to edit my entity no errors shows but the modifications aren't applied.
When I dump my entity after form validation the modifications are applied but aren't flushed to database.

Class definition :
```
     /**
     * @var ArrayCollection|Media[]
     * @ORM\Column(name="documents",type="media_collection")
     */
    private $documents;

     /**
     * Add document
     *
     * @param Media $document
     *
     * @return OfferRange
     */
    public function addDocument(Media $document)
    {
        $this->documents[] = $document;
        return $this;
    }

    /**
     * Remove document
     *
     * @param Media $document
     */
    public function removeDocument(Media $document)
    {
        $this->documents->removeElement($document);
    }

    /**
     * Get documents
     *
     * @return Media[]|ArrayCollection|media_collection
     */
    public function getDocuments()
    {
        return $this->documents;
    }
```

Class form type:
```
$builder->add('documents', MediaCollectionType::class, array('conf' => 'default', 'entry_options' => [ 'allow_alt' => false]));
```
Thanks you in advance.

**Comment by Arkounay** [comment]
Hi,

Unlike classic collections, media_collection are a bit special and require setter usage insead of `add` and `remove` functions.

So I think if you try to remove your `addDocument` and `removeDocument` and add the following it will work : 

```
    public function setDocuments($document): void
    {
        $this->docments = $documents;
    }
```

**Comment by mitjana** [comment]
Hi,
Thank you for your quick reply.
That solved my problem, but when deleting all Media from a collection the first value is set to null and other are erased is it intented ? 
It caused some problems with my twig view but was easily solvable.

Anyway thank you again for this great bundle. 👍
