### ISSUE TITLE
Wrong file path leading to errors

### ISSUE THREAD

**Issue by mitjana** [artgris/MediaBundle#18]
Hi,
I used your bundle and it was working really well but I don't now if it is because I changed the config directory from now when I want to import a document the path is saved like that :
/app_dev.php/manager/file/file.pdf?conf=default 
and it cause issues when I want to retrieve the file.

Please ask if you need any other informations.
Thank.

**Comment by artgris** [comment]
Hi, @mitjana , can you share your config ? your path look like a private conf (when 'directory' is not in public/web) 

This could help you:
https://github.com/artgris/FileManagerBundle/issues/26
https://github.com/artgris/FileManagerBundle/commit/df7700e0534ff94164b51dbd4f59ee95c5921c82

**Comment by mitjana** [comment]
Hi, thank you for responding my post but we fixed that problem. 
It was because the path was not in public/web , my boss helped me to fix this.
I don't remember how we did it but if someone need it please re-open this issue and I will try to find.

Anyway thank you for your support and your bundle.
