### ISSUE TITLE
Init with n elements

### ISSUE THREAD

**Issue by Quovandius** [artgris/MediaBundle#19]
Hello,

I have a little problem. I have try to configure the parameter  `init_with_n_elements` and nothing has happened.

I have try to update in vendor the file field_media.html.twig at line 
`        {% set attr = attr|merge({'data-init-with-n-elements': data_init_with_n_elements ? data_init_with_n_elements : 1}) %}`

How can i update this ?

**Comment by artgris** [comment]
Hi @Quovandius, I can't reproduce your problem. Do you have more details or example code, plz ?
