### ISSUE TITLE
Media with path null

### ISSUE THREAD

**Issue by Quovandius** [artgris/MediaBundle#21]
Hello,

I have an information, not a question ^^

When i have used a media collection, first element was initialized. 
But if i didn't fill any information and i save the form, a media was created with null path and null alt.

So if try to display collection with : 
```
{% for document in customer.documents %}
    <img src="{{ asset(document.path) }}" alt="{{ document.alt }}"
              class="pict-thumbnail img-thumbnail">
 {% endfor %
```}

I have a bug. The html page on load try to reach this assets with a 301 http request. And when i refresh another page, that's load the root page /

So i have avoid this error with this test : 
     ```
          {% if customer.documents is not empty %}
                    {% for document in customer.documents %}

                        {% if document.path is not null %}
                            <img src="{{ asset(document.path) }}" alt="{{ document.alt }}"
                                 class="pict-thumbnail img-thumbnail">
                        {% endif %}

                    {% endfor %}
                {% endif %}
```

The best improvment must be to avoid save a media with null path.
Thanks fors this bundle =)

**Comment by Arkounay** [comment]
Hi, thanks for your feedback.
Are you using the latest version of the bundle ? (2.2)

That's strange, the media collection in the database should be empty and not contain an object with null properties.

**Comment by Quovandius** [comment]
No i'm use version 1.1

I will update and try again.
