### ISSUE TITLE
SF4 MediaBundle / easyadmin :  collection javascript

### ISSUE THREAD

**Issue by johan-Rm** [artgris/MediaBundle#24]
Hi,

I use SF4 and easyadmin, I override AdminController to add the imageCollection field :
```
/**
     * @param $entity
     * @param $view
     * @return \Symfony\Component\Form\FormBuilder
     */
    protected function createPhotoEntityFormBuilder($entity, $view)
    {
      $formBuilder = parent::createEntityFormBuilder($entity, $view);
      $formBuilder->add('image', MediaType::class, [
          'conf' => 'default'
      ])
      ->add('imageCollection', MediaCollectionType::class, [
          'conf' => 'default'
      ]);

      $formBuilder->get('image')->addModelTransformer(new CallbackTransformer(
        function ($pathAsMedia) {
            $media = new Media();
            if(null !== $pathAsMedia) {
              $media->setPath($pathAsMedia);
            }

            return $media;
        },
        function ($imageAsString) {

          return $imageAsString->getPath();
        }
      ));

      return $formBuilder;
    }
```

But when display the form I see an javascript error linked to the imageCollection field.

> TypeError: $this.collection is not a function media.js:135:9

Someone can help me ?

thanks

**Comment by Arkounay** [comment]
The collection part requires [ninsuo/symfony-collection](https://github.com/ninsuo/symfony-collection)'s JavaScript, ([artgris/mediaBundle#prerequisites](https://github.com/artgris/mediaBundle#prerequisites)) it's probably what's missing. (it's also requiring jQuery UI for drag & drop but I think it's not mandatory)

**Comment by johan-Rm** [comment]
thanks again
