### ISSUE TITLE
Issue with Crop since last gregwar update

### ISSUE THREAD

**Issue by gobolabs** [artgris/MediaBundle#30]
Hello, 

(Fyi)

To make Crop working, 

we was forced to apply some modifications since the last update by the Gregwar Team.

[Commit here](https://github.com/Gregwar/Image/commit/25fbb91a95d41d44587ee7ca8923745b66221a7d#diff-b22b516242ef19dd70841811afd9b551)

For now we have overrided the AjaxController and modified the ajaxCrop method.

Before :
`
if ($src[0] == '/') {
            $src = $request->getSchemeAndHttpHost() . $src;
        }
`

After:
`
$src = $this->getParameter('kernel.project_dir') .'/<ourPublicFolder>' . $src;     
`

**Comment by gobolabs** [comment]
Note that it's a temporary patch until an update from the Artgris Team :) Do not follow it if you don’t have the problem a this moment.

**Comment by Arkounay** [comment]
Hello, thank you for your contribution @gobolabs :+1:
