### ISSUE TITLE
Error on symfony 3.4.27

### ISSUE THREAD

**Issue by jimiero** [artgris/MediaBundle#38]
Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service "filemanager_configuration" has a dependency on a non-existent service "parameter_bag"

@artgris how to solve that error?

**Comment by danabrey** [comment]
It looks like the bundle requires the `parameter_bag` service which was introduced in Symfony 4.1. It would be good to declare the dependency on SF4.1 in `composer.json`. :)
