### ISSUE TITLE
Crop not working for me

### ISSUE THREAD

**Issue by KlausK18** [artgris/MediaBundle#40]
I have configured everything as documentation said and it is everything working fine, but not the cropping.
In html I can see the modal thath should apear when I click on the image, but image or divs that contains it didnt have modal relationships to it.

On my ExampleType.php I have:

->add('image', MediaType::class, [
                'conf' => 'default',
                'allow_crop' => true,
                'crop_options' => array(
                    'display_crop_data' => true,
                    'allow_flip' => true,       
                    'allow_rotation' => true,   
                    'ratio' => false            
                ),
            ])

And still not working. 
Thankyou!

**Comment by artgris** [comment]
Maybe b5b17ce490e9e9a0ae02243211c1a501e8de024c fixed your error. try last release...
