### ISSUE TITLE
Using readonly and required together

### ISSUE THREAD

**Issue by WouterCypers** [artgris/MediaBundle#41]
I am using `MediaType` in EasyAdminBundle. When setting `required` and `readonly` both to true, `readonly` does not work. This happens because a readonly field is not editable and therfore can't be required.

In my case, I want the user to see the path of the selected file, but not to edit it directly. However, the user is required to select a file...

I see 2 solutions to this problem:
1. Use a hidden input field and show the file path in a regular fashion (in a `div`)
2. Don't use `readonly="readonly` but instead do something like this:
```html
<input type="text" class="readonly" required />

<script>
    $(".readonly").on('keydown paste', function(e){
        e.preventDefault();
    });
</script>
```

Any thoughts?

More information on this topic: https://stackoverflow.com/questions/12777751/html-required-readonly-input-in-form/43482585

**Comment by artgris** [comment]
I think you've already found your solution... both sound good to me.
