### ISSUE TITLE
SF4.4.4 form types not working

### ISSUE THREAD

**Issue by DylanGD** [artgris/MediaBundle#43]
Hello,

```# Doctrine Configuration
doctrine:
    dbal:
        ...
        types:
            media: Artgris\Bundle\MediaBundle\Form\Type\MediaType
            media_collection: Artgris\Bundle\MediaBundle\Form\Type\MediaCollectionType
```
Get the following error : 

```Argument 2 passed to Doctrine\DBAL\Types\TypeRegistry::register() must be an instance of Doctrine\DBAL\Types\Type, instance of Artgris\Bundle\MediaBundle\Form\Type\MediaCollectionType given, called in /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/Type.php on line 246```

* symfony : 4.4.4
* symfony/dbal : 2.10.1
* artgris/media-bundle : 5.2.6

Thanks you

**Comment by jgendera** [comment]
Hi Dylan, I think you confused form types with doctrine types. 

The exact usage is documented here: https://github.com/artgris/MediaBundle#usage

As for Doctrine, you map those fields as string or array. It's also described in docs above.
