### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by dekdek2** [artgris/MediaBundle#45]
Hello,

here is my configuration:

Symfony: 4.4.3
Doctrine: 2.7.0

Unfortunately, I cannot integrate your bundle into my project.
Error during "composer require artgris / media-bundle":
Installation failed, reverting ./composer.json to its original content.

Can you help me solve this problem.

Thank you.

**Comment by artgris** [comment]
Probably a compatibility issue. maybe try last release.
