### ISSUE TITLE
Doesn't compatible with symfony 5

### ISSUE THREAD

**Issue by vanthai-jvit** [artgris/MediaBundle#46]
The bundle is great. But it doesn't work on Symfony 5
![image](https://user-images.githubusercontent.com/10457634/85112377-be15b980-b23f-11ea-878f-cf6be5088bc3.png)

**Comment by artgris** [comment]
Hi, I know, i'm waiting Gregwar/ImageBundle symfony 5 compatibility. You can use branch 6.x in the meantime where i removed this dependency

**Comment by artgris** [comment]
6.0.1 is available but I removed my gImage twig extension.
